[package]
name = "yew_server"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@amethyst-engine.org>"]
edition = "2018"

[dependencies]
websocket = "0.22.0"
failure = "0.1"
log = "0.4.6"

[dev-dependencies]
tempdir = "0.3.7"