[package]
name = "server"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@amethyst-engine.org>"]
edition = "2018"

[dependencies]
websocket = "0.22.0"
failure = "0.1"
log = "0.4.6"
httparse = "1.3.3"
http = "0.1.17"
clap = "2.33.0"
env_logger = "0.6.1"

[dev-dependencies]
tempdir = "0.3.7"
